name: Master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: setup gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
      - name: run assemble
        run: ./gradlew assemble
      - name: run ktlintCheck
        run: ./gradlew ktlintCheck
      - name: run lintDebug
        run: ./gradlew lintDebug
      - name: run detektCheck
        run: ./gradlew detektCheck
