name: Pre-Merge

on:
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run assemble
      run: ./gradlew assemble

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: run ktlintCheck
      run: ./gradlew ktlintCheck
    - name: run lintDebug
      run: ./gradlew lintDebug
    - name: upload lint results
      uses: actions/upload-artifact@v2
      with:
        name: lint
        path: app/build/reports/
    - name: run detekt
      run: ./gradlew detekt
    - name: upload detekt results
      uses: actions/upload-artifact@v2
      with:
        name: detekt
        path: build/reports/
