name: Pre-Merge

on:
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: run assemble
      run: ./gradlew assemble

  ktlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: run ktlintCheck
      run: ./gradlew ktlintCheck

  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: run lintDebug
      run: ./gradlew lintDebug
    - name: upload lint results
      uses: actions/upload-artifact@v2
      with:
        name: lint
        path: app/build/reports/
    - name: run detektCheck
      run: ./gradlew detektCheck
    - name: upload detekt results
      uses: actions/upload-artifact@v2
      with:
        name: detekt
        path: build/reports/

  danger:
    needs: [ analyze ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: '2.6'
    - name: install bundler 2.1.2
      run: gem install bundler:2.1.2
    - uses: actions/cache@v2.1.6
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: download lint results
      uses: actions/download-artifact@v2
      with:
        name: lint
        path: app/build/reports/
    - name: download detekt results
      uses: actions/download-artifact@v2
      with:
        name: detekt
        path: build/reports/
    - uses: MeilCli/danger-action@v5.4.3
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-ci'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_API_TOKEN }}
